/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microtechmd_pda_control_platform_JNIInterface */

#ifndef _Included_com_microtechmd_pda_control_platform_JNIInterface
#define _Included_com_microtechmd_pda_control_platform_JNIInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_open
        (JNIEnv *, jobject);

/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_close
        (JNIEnv *, jobject);
/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    battery
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_battery
        (JNIEnv *, jobject);
/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    turnOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_turnOff
        (JNIEnv *, jobject);
/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    ready
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_ready
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    send
 * Signature: (IIIIII[B)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_send
        (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    query
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_query
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    switchLink
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_switchLink
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    setLED
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_setLED
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microtechmd_pda_control_platform_JNIInterface
 * Method:    getLED
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_pda_control_platform_JNIInterface_getLED
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_microtechmd_pda_control_platform_JNIInterface_Callback */

#ifndef _Included_com_microtechmd_pda_control_platform_JNIInterface_Callback
#define _Included_com_microtechmd_pda_control_platform_JNIInterface_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
